image: ubuntu:18.04
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get -y upgrade
          - apt-get -y install g++ make python2.7 python3.6 python3.7 python-tox
          - tox
